version: '3'
services:
  api:
    build:
      context: . 
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/api:/go/src/api
    networks: 
      - my_network
  mysql:
    build: ./docker/db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    hostname: mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d
    networks: 
      - my_network
swagger:
    image: swaggerapi/swagger-editor
    environment:
      #API_URL: ./docker/swagger/swagger-editor.yml
      SWAGGER_FILE: /data/swagger-editor.yml
    ports:
      - "8081:8080"
    volumes:
      - ./docker/swagger:/data
    networks:
      - my_network

# 同じnetworksに属するコンテナ間は認識できて通信可能に
networks:
  my_network:

  


